### PR TITLE
Fix callProcedure on Windows with UNICODE

### LINKED ISSUE #120: [BUG] callProcedure does not work on Windows.
**Describe your system**
* `odbc` Package Version: 2.3.4
* ODBC Driver: IBM i Access ODBC Driver (13.64.24)
* Database Name: Db2 for i
* Database Version: x
* Database OS: IBM i
* Node.js Version: 12.13.1
* Node.js OS: Windows

**Describe the bug**

I am getting, what could be an encoding issue with odbc.

```
[IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token  was not valid. Valid tokens: ( CL END GET SET TAG CALL DROP FREE HOLD LOCK OPEN WITH ALTER.
````

When running: `const results = await connection.callProcedure(null, 'BARRY', 'ABCD_PGM', [ds, '']);`

But I can run the usual `executeStatement` with no problems.

I am only getting this issue on Windows. I tested on my Macbook and the same code works.

**Expected behavior**
Return of output parameters.

image

**To Reproduce**
1. Connect to database with options:

```js
  connectionString = [
    `Driver=IBM i Access ODBC Driver`,
    `System=${process.env.DB2_SYSTEM}`,
    `UID=${process.env.DB2_UID}`,
    `Password=${process.env.DB2_PASSWORD}`,
    `DBQ=,*USRLIBL`,
    `Naming=1`,
  ].join(';'),
```

2. Call a stored procedure with one in parameter and one out parameter. (as above)

**Additional context**

>The source looked good, but everything got converted to 3f...

```
t=e89c 15:19:39.373 [00]                  NLS: NL CONV:cvt=6107 scp=1202 tcp=273 siso=1 pad=4 s*=0x205709fc9a0 sl=18 t*=0x20570a12740 tl=30
t=e89c 15:19:39.373 [00]                  NLS: src:18 
[00001] 7b2043414c4c20422e4120283f2c3f29207d                              <{ CALL B.A (?,?) }              > [#...<<...........'              ]
t=e89c 15:19:39.373 [00]                  NLS: tgt:9 
[00001] 3f3f3f3f3f3f3f3f3f                                                <?????????                       > [.........                       ]
```

> The text comes back in EBCDIC, the important hex is here: 403f40. space, substitution character, space.

```
[00002] f1f0f40000006d380201110063e396928595403f40a681a2409596a340a58193  <......m8....c.....@?@...@...@...> [104..._......Token . was not val]
```

image

### PR DESCRIPTION
**Pull request by kadler**
The SQL generated to in callProcedure is a standard C string, but passed
to SQLExecDirectW when UNICODE is defined. Instead, it needs to be
generated as a wide string.

Note that printf format specifies for strings on Windows are a bit
*unique* as %s means char* with printf, but wchar_t* with wprintf and
vice-versa for %S.
https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170#type-field-characters

Fixes #120

Signed-off-by: Kevin Adler <kadler@us.ibm.com>

### CODE REVIEW

File: src/odbc_connection.cpp [hunk 1]
```diff
@@ -1809,8 +1809,15 @@ class CallProcedureAsyncWorker : public ODBCAsyncWorker {
...
 
-      data->sql = new SQLTCHAR[255]();
+      data->sql = new SQLTCHAR[255];
+#ifndef UNICODE
       sprintf((char *)data->sql, "{ CALL %s (%s) }", combinedProcedureName, parameterString);
+#else
+      // Note: On Windows, %s and %S change their behavior depending on whether
+      // it's passed to a printf function or a wprintf function. Since we're passing
+      // a narrow string to a wide function, we need to use %S.
+      swprintf(data->sql, 255, L"{ CALL %S (%S) }", combinedProcedureName, parameterString);
```
Comment (markdirish) [inline src/odbc_connection.cpp:1819]: Is this not a wide string passed to a wide function? If `UNICODE` is defined, `data->sql` will be an `SQLWCHAR`, and you create a wide string with `L"..."`, but maybe there is something I don't get.

**Review by markdirish — COMMENTED** [review]
Just some lingering confusion about narrow/wide in `swprintf`

File: src/odbc_connection.cpp (hunk 1 above)
Comment (kadler) [reply src/odbc_connection.cpp:1819]: I was referring to the values associated with the %S, ie. combinedProcedureName and parameterString, though I see that parameterString actually has the same problem where it's SQLTCHAR but being created as a C string. I'll fix that too.

**Review by markdirish — APPROVED** [review]
LGTM
